# 1. Cấu hình kết nối SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SWD392_AIVES;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=12345

# 2. Cấu hình JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=MySuperSecretKeyForAIVESJWTAuthentication2026VeryLong
jwt.expiration=36000