package com.example.swd392_se1907_aives.service;
import java.util.*;
import com.example.swd392_se1907_aives.domain.entity.*;
public final class Views {
 public static Map<String,Object> map(Object... pairs) { Map<String,Object> result = new LinkedHashMap<>(); for(int i=0;i<pairs.length;i+=2) result.put((String)pairs[i],pairs[i+1]); return result; }
 public static Map<String,Object> user(User u) { return map("userId",u.getUserId(),"username",u.getUsername(),"fullName",u.getFullName(),"email",u.getEmail(),"role",u.getRole().getRoleName(),"status",u.getUserStatus()); }
 public static Map<String,Object> question(Question q) { return map("questionId",q.getQuestionId(),"subjectId",q.getSubject().getSubjectId(),"documentId",q.getDocument()==null?null:q.getDocument().getDocumentId(),"createdBy",q.getCreatedBy().getUserId(),"topic",q.getTopic(),"questionContent",q.getQuestionContent(),"bloomLevel",q.getBloomLevel(),"source",q.getSource(),"status",q.getStatus(),"createdAt",q.getCreatedAt(),"approvedAt",q.getApprovedAt()); }
 public static Map<String,Object> rubric(Rubric r) { return map("rubricId",r.getRubricId(),"questionId",r.getQuestion().getQuestionId(),"criteriaName",r.getCriteriaName(),"maxScore",r.getMaxScore(),"guideline",r.getGuideline()); }
 public static Map<String,Object> document(SubjectDocument d) { return map("documentId",d.getDocumentId(),"subjectId",d.getSubject().getSubjectId(),"title",d.getTitle(),"fileType",d.getFileType(),"status",d.getStatus(),"uploadedAt",d.getUploadedAt(),"uploadedBy",d.getUploadedBy().getUserId()); }
 public static Map<String,Object> exam(ExamSession e) { return map("examId",e.getExamId(),"subjectId",e.getSubject().getSubjectId(),"createdBy",e.getCreatedBy().getUserId(),"examName",e.getExamName(),"startTime",e.getStartTime(),"endTime",e.getEndTime(),"maxMainQuestions",e.getMaxMainQuestions(),"maxFollowUpQuestions",e.getMaxFollowUpQuestions(),"answerTimeLimitSeconds",e.getAnswerTimeLimitSeconds(),"status",e.getStatus()); }
 public static Map<String,Object> schedule(ExamSchedule s) { return map("scheduleId",s.getScheduleId(),"examId",s.getExamSession().getExamId(),"examName",s.getExamSession().getExamName(),"studentId",s.getStudent().getUserId(),"studentName",s.getStudent().getFullName(),"allocatedStartTime",s.getAllocatedStartTime(),"allocatedEndTime",s.getAllocatedEndTime(),"actualStartTime",s.getActualStartTime(),"actualEndTime",s.getActualEndTime(),"status",s.getStatus()); }
 public static Map<String,Object> log(InterviewLog l) { return map("logId",l.getLogId(),"scheduleId",l.getExamSchedule().getScheduleId(),"questionId",l.getQuestion()==null?null:l.getQuestion().getQuestionId(),"parentLogId",l.getParentLog()==null?null:l.getParentLog().getLogId(),"sequenceNumber",l.getSequenceNumber(),"questionContent",l.getQuestionContent(),"questionType",l.getQuestionType(),"studentAnswerTranscript",l.getStudentAnswerTranscript(),"askedAt",l.getAskedAt(),"answeredAt",l.getAnsweredAt(),"timeTakenSeconds",l.getTimeTakenSeconds(),"hasAnswerAudio",l.getAnswerAudioUrl()!=null); }
}
